INSERT INTO movie_genre (movie, genre) VALUES (2, 1),
                                              (2, 3),
                                              (2, 5),
                                              (2, 4),
                                              (3, 1),
                                              (3, 4),
                                              (3, 5),
                                              (3, 6),
                                              (4, 1),
                                              (5, 1),
                                              (5, 4),
                                              (5, 5),
                                              (5, 6);