version: 4.28.0
services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres:/data/postgres2
    ports:
      - 5433:5432
    networks:
      - postgres
    restart: unless-stopped

    logging:
      options:
        max-size: 10m
        max-file: 3
networks:
  postgres:
    driver: bridge
volumes:
  postgres: